---
keybinds:
    Normal:
        - action: [GoToTab: 1,]
          key: [F: 1,]
        - action: [GoToTab: 2,]
          key: [F: 2,]
        - action: [GoToTab: 3,]
          key: [F: 3,]
        - action: [GoToTab: 4,]
          key: [F: 3,]
        - action: [NewTab,]
          key: [F: 5,]
        - action: [NewPane: Right, NewPane: Right,]
          key: [F: 6,]
        - action: [NewPane: Right, NewPane: Right,]
          key: [F: 6,]
