name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Add WASM target
      run: rustup target add wasm32-wasi
    - name: Install cargo-make
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: --debug cargo-make
    - name: Run Tests
      uses: actions-rs/cargo@v1
      with:
        command: make

  format:
    name: Check Formatting
    runs-on: ubuntu-latest

    steps:
    - name: Install cargo-make
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: --debug cargo-make
    - name: Check Format
      uses: actions-rs/cargo@v1
      with:
        command: make
        args: check-format

  clippy:
    name: Check For Clippy Lints
    runs-on: ubuntu-latest

    steps:
    - name: Install cargo-make
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: --debug cargo-make
    - name: Check Lints
      uses: actions-rs/cargo@v1
      with:
        command: make
        args: clippy -D clippy::all
